@baseUrl = http://localhost:3000

# RECADOS
### 
GET {{baseUrl}}/recados
?limit=10
&offset=0
Authorization: Bearer 123456
###
GET {{baseUrl}}/recados/47
Authorization: Bearer 123456

###
POST {{baseUrl}}/recados
Content-Type: application/json

{
    "texto": "Comprar leite create",
    "deId": 17,
    "paraId": 19
}

###
PATCH {{baseUrl}}/recados/26
Content-Type: application/json

{
    "texto":"Novo Texto"
}
###
DELETE {{baseUrl}}/recados/26






# PESSOAS
### 
GET {{baseUrl}}/pessoas/?limit=30&offset=0&user=tatiana
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIzLCJlbWFpbCI6InRhdGlhbmFwYWNoZWNvMDlAZW1haWwuY29tIiwiaWF0IjoxNzc5MTk5NTgzLCJleHAiOjE3NzkyMDMxODMsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCJ9.s7WmYvDEuuQ9Vho9mrcNq8G_zFbGznTGhL9xTrGt8DM
###
GET {{baseUrl}}/pessoas/14

###
POST {{baseUrl}}/pessoas
Content-Type: application/json

{
    "email":"tatianapacheco09@email.com",
    "password":"123456",
    "nome":"Tatiana Pacheco"
}

###
PATCH {{baseUrl}}/pessoas/21
Content-Type: application/json

{
    "nome":"Tati"
}
###
DELETE {{baseUrl}}/pessoas/14




### 
POST {{baseUrl}}/auth
Content-Type: application/json

{
    "email":"tatianapacheco09@email.com",
    "password":"123456"
}


###