@baseUrl = http://localhost:3003
@authToken = {{authenticate.response.body.accessToken}}
@refreshToken = {{authenticate.response.body.refreshToken}}
# RECADOS
### 
GET {{baseUrl}}/recados
?limit=10
&offset=0
Authorization: Bearer {{authToken}}
###
GET {{baseUrl}}/recados/47
Authorization: Bearer {{authToken}}

###
POST {{baseUrl}}/recados
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "texto": "Comprar leite create",
    "paraId": 19
}

###
PATCH {{baseUrl}}/recados/50
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "texto":"Novo Texto",
    "lido": false
}
###
DELETE {{baseUrl}}/recados/48
Authorization: Bearer {{authToken}}






# PESSOAS
### 
GET {{baseUrl}}/pessoas/?limit=30&offset=0&user=tatiana
Authorization: Bearer {{authToken}}
###
GET {{baseUrl}}/pessoas/23
Authorization: Bearer {{authToken}}
###
POST {{baseUrl}}/pessoas
Content-Type: application/json

{
    "email":"teste123@email.com",
    "password":"123456",
    "nome":"Tatiana Pacheco"
}

###
PATCH {{baseUrl}}/pessoas/23
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "nome":"Tatiana"
}
###
DELETE {{baseUrl}}/pessoas/25
Authorization: Bearer {{authToken}}




### Autenticação
# @name authenticate
POST {{baseUrl}}/auth
Content-Type: application/json

{
    "email":"tatianapacheco09@email.com",
    "password":"123456"
}


### Refresh Token
# @name authenticate
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
    "refreshToken":"{{refreshToken}}"
}






# Uploads
### Foto da Pessoa
POST {{baseUrl}}/pessoas/upload-picture
Content-Type: multipart/form-data; boundary=----BoundaryDelimitadorHttp
Authorization: Bearer {{authToken}}

------BoundaryDelimitadorHttp
Content-Disposition: form-data; name="file"; filename="images.jpg"
Content-Type: image/jpeg

< ./dev/images/images.jpg

------BoundaryDelimitadorHttp--

### Ver Foto
GET {{baseUrl}}/pictures/23.png