@baseUrl = http://localhost:3000

# RECADOS
### 
GET {{baseUrl}}/recados
?limit=10
&offset=0
Authorization: Bearer 123456
###
GET {{baseUrl}}/recados/47
Authorization: Bearer 123456

###
POST {{baseUrl}}/recados
Content-Type: application/json

{
    "texto": "Comprar leite create",
    "deId": 17,
    "paraId": 19
}

###
PATCH {{baseUrl}}/recados/26
Content-Type: application/json

{
    "texto":"Novo Texto"
}
###
DELETE {{baseUrl}}/recados/26






# PESSOAS
### 
GET {{baseUrl}}/pessoas/?limit=30&offset=0&user=tatiana
###
GET {{baseUrl}}/pessoas/14

###
POST {{baseUrl}}/pessoas
Content-Type: application/json

{
    "email":"tatianapacheco12@email.com",
    "password":"123456",
    "nome":"Tatiana Pacheco"
}

###
PATCH {{baseUrl}}/pessoas/14
Content-Type: application/json

{
    "password":"123456"
}
###
DELETE {{baseUrl}}/pessoas/14